In [1]:
import pandas as pd
import numpy as np

# positive data

In [2]:
positive_substance_data = pd.read_csv(
    '/data/project/ubrite/covid19-hackathon/Team4_staging_area/parsed_data/observation_positive.csv'
).set_index('PERSON_ID')

In [3]:
positive_substance_data.head(10)

                                  VALUE_AS_STRING OBSERVATION_SOURCE_VALUE
PERSON_ID
1                                            None          SHX Alcohol use
1                                            None  SHX Substance abuse use
1                                   Former smoker          SHX Tobacco use
1          Body mass index (BMI) 40.0-44.9, adult                   Z68.41
2                                         Current          SHX Alcohol use
2                                            None  SHX Substance abuse use
2                                    Never smoker          SHX Tobacco use
3                                            None          SHX Alcohol use
3                                            None  SHX Substance abuse use
3                                    Never smoker          SHX Tobacco use

In [4]:
# remove substance abuse
positive_substance_data = positive_substance_data[~positive_substance_data['OBSERVATION_SOURCE_VALUE'].str.contains('Substance')]

In [5]:
positive_substance_data["OBSERVATION_SOURCE_VALUE"] = positive_substance_data["OBSERVATION_SOURCE_VALUE"].str.split('.').str[0]
positive_substance_data.head(10)

                                  VALUE_AS_STRING OBSERVATION_SOURCE_VALUE
PERSON_ID
1                                            None          SHX Alcohol use
1                                   Former smoker          SHX Tobacco use
1          Body mass index (BMI) 40.0-44.9, adult                      Z68
2                                         Current          SHX Alcohol use
2                                    Never smoker          SHX Tobacco use
3                                            None          SHX Alcohol use
3                                    Never smoker          SHX Tobacco use
3          Body mass index (BMI) 50.0-59.9, adult                      Z68
4                                            None          SHX Alcohol use
4                                    Never smoker          SHX Tobacco use

In [6]:
positive_substance_data['VALUE_AS_STRING'][positive_substance_data['VALUE_AS_STRING'].str.contains('Current')]="Current"
positive_substance_data["observation_combined"] = positive_substance_data["OBSERVATION_SOURCE_VALUE"] + " " + positive_substance_data["VALUE_AS_STRING"]

In [7]:
positive_substance_data.head(50)

,VALUE_AS_STRING,OBSERVATION_SOURCE_VALUE,observation_combined
PERSON_ID,,,
1,None,SHX Alcohol use,SHX Alcohol use None
1,Former smoker,SHX Tobacco use,SHX Tobacco use Former smoker
1,"Body mass index (BMI) 40.0-44.9, adult",Z68,"Z68 Body mass index (BMI) 40.0-44.9, adult"
2,Current,SHX Alcohol use,SHX Alcohol use Current
2,Never smoker,SHX Tobacco use,SHX Tobacco use Never smoker
3,None,SHX Alcohol use,SHX Alcohol use None
3,Never smoker,SHX Tobacco use,SHX Tobacco use Never smoker
3,"Body mass index (BMI) 50.0-59.9, adult",Z68,"Z68 Body mass index (BMI) 50.0-59.9, adult"
4,None,SHX Alcohol use,SHX Alcohol use None
4,Never smoker,SHX Tobacco use,SHX Tobacco use Never smoker
5,Current,SHX Alcohol use,SHX Alcohol use Current
5,Current,SHX Tobacco use,SHX Tobacco use Current
5,"Body mass index (BMI) 26.0-26.9, adult",Z68,"Z68 Body mass index (BMI) 26.0-26.9, adult"
6,None,SHX Alcohol use,SHX Alcohol use None
6,Former smoker,SHX Tobacco use,SHX Tobacco use Former smoker
6,"Body mass index (BMI) 60.0-69.9, adult",Z68,"Z68 Body mass index (BMI) 60.0-69.9, adult"
7,None,SHX Alcohol use,SHX Alcohol use None
7,Never smoker,SHX Tobacco use,SHX Tobacco use Never smoker
7,"Body mass index (BMI) 31.0-31.9, adult",Z68,"Z68 Body mass index (BMI) 31.0-31.9, adult"
8,None,SHX Alcohol use,SHX Alcohol use None
8,Never smoker,SHX Tobacco use,SHX Tobacco use Never smoker
8,"Body mass index (BMI) 39.0-39.9, adult",Z68,"Z68 Body mass index (BMI) 39.0-39.9, adult"
9,None,SHX Alcohol use,SHX Alcohol use None
9,Never smoker,SHX Tobacco use,SHX Tobacco use Never smoker
10,Current,SHX Alcohol use,SHX Alcohol use Current
10,Never smoker,SHX Tobacco use,SHX Tobacco use Never smoker
10,"Body mass index (BMI) 30.0-30.9, adult",Z68,"Z68 Body mass index (BMI) 30.0-30.9, adult"
11,Former,SHX Alcohol use,SHX Alcohol use Former
11,Current,SHX Tobacco use,SHX Tobacco use Current
11,"Body mass index (BMI) 28.0-28.9, adult",Z68,"Z68 Body mass index (BMI) 28.0-28.9, adult"
12,None,SHX Alcohol use,SHX Alcohol use None
12,Former smoker,SHX Tobacco use,SHX Tobacco use Former smoker
12,"Body mass index (BMI) 31.0-31.9, adult",Z68,"Z68 Body mass index (BMI) 31.0-31.9, adult"
13,Current,SHX Alcohol use,SHX Alcohol use Current
14,None,SHX Alcohol use,SHX Alcohol use None
14,Never smoker,SHX Tobacco use,SHX Tobacco use Never smoker
15,Current,SHX Alcohol use,SHX Alcohol use Current
15,Never smoker,SHX Tobacco use,SHX Tobacco use Never smoker
15,"Body mass index (BMI) 35.0-35.9, adult",Z68,"Z68 Body mass index (BMI) 35.0-35.9, adult"
16,Current,SHX Alcohol use,SHX Alcohol use Current
16,Former smoker,SHX Tobacco use,SHX Tobacco use Former smoker
16,"Body mass index (BMI) 29.0-29.9, adult",Z68,"Z68 Body mass index (BMI) 29.0-29.9, adult"
17,None,SHX Alcohol use,SHX Alcohol use None
17,Never smoker,SHX Tobacco use,SHX Tobacco use Never smoker
17,"Body mass index (BMI) 30.0-30.9, adult",Z68,"Z68 Body mass index (BMI) 30.0-30.9, adult"
19,Former,SHX Alcohol use,SHX Alcohol use Former
19,Former smoker,SHX Tobacco use,SHX Tobacco use Former smoker
20,Current,SHX Alcohol use,SHX Alcohol use Current
20,Former smoker,SHX Tobacco use,SHX Tobacco use Former smoker
20,"Body mass index (BMI) 50.0-59.9, adult",Z68,"Z68 Body mass index (BMI) 50.0-59.9, adult"

In [8]:
positive_substance_data = positive_substance_data.drop(["VALUE_AS_STRING", "OBSERVATION_SOURCE_VALUE"], axis=1)

In [9]:
positive_substance_cat = pd.get_dummies(positive_substance_data).groupby(level=0).sum()
positive_substance_cat.head()

,observation_combined_SHX Alcohol use Current,observation_combined_SHX Alcohol use Former,observation_combined_SHX Alcohol use None,observation_combined_SHX Alcohol use Unknown,observation_combined_SHX Alcohol use Within the past year,observation_combined_SHX Tobacco use Current,observation_combined_SHX Tobacco use Former smoker,observation_combined_SHX Tobacco use Never smoker,"observation_combined_SHX Tobacco use Smoker, current status unknown",observation_combined_SHX Tobacco use Unknown if ever smoked,...,"observation_combined_Z68 Body mass index (BMI) 37.0-37.9, adult","observation_combined_Z68 Body mass index (BMI) 38.0-38.9, adult","observation_combined_Z68 Body mass index (BMI) 39.0-39.9, adult","observation_combined_Z68 Body mass index (BMI) 40.0-44.9, adult","observation_combined_Z68 Body mass index (BMI) 45.0-49.9, adult","observation_combined_Z68 Body mass index (BMI) 50-59.9 , adult","observation_combined_Z68 Body mass index (BMI) 50-59.9, adult","observation_combined_Z68 Body mass index (BMI) 50.0-59.9, adult","observation_combined_Z68 Body mass index (BMI) 60.0-69.9, adult","observation_combined_Z68 Body mass index (BMI) 70 or greater, adult"
PERSON_ID,,,,,,,,,,,,,,,,,,,,,
1,0,0,1,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
positive_substance_cat.to_csv('/data/project/ubrite/covid19-hackathon/Team4_staging_area/parsed_data/positive_observation_categorical.csv'
                      , index=True)

# Negative

In [11]:
negative_substance_data = pd.read_csv(
    '/data/project/ubrite/covid19-hackathon/Team4_staging_area/parsed_data/observation_negative.csv'
).set_index('PERSON_ID')

In [12]:
negative_substance_data.head()

                                  VALUE_AS_STRING OBSERVATION_SOURCE_VALUE
PERSON_ID
100000                                    Current          SHX Alcohol use
100000                                       None  SHX Substance abuse use
100000                              Former smoker          SHX Tobacco use
100000     Body mass index (BMI) 32.0-32.9, adult                   Z68.32
100001                                       None          SHX Alcohol use

In [13]:
# remove substance abuse
negative_substance_data = negative_substance_data[~negative_substance_data['OBSERVATION_SOURCE_VALUE'].str.contains('Substance')]

In [14]:
negative_substance_data["OBSERVATION_SOURCE_VALUE"] = negative_substance_data["OBSERVATION_SOURCE_VALUE"].str.split('.').str[0]

In [15]:
negative_substance_data['VALUE_AS_STRING'][negative_substance_data['VALUE_AS_STRING'].str.contains('Current')]="Current"
negative_substance_data["observation_combined"] = negative_substance_data["OBSERVATION_SOURCE_VALUE"] + " " + negative_substance_data["VALUE_AS_STRING"]

In [16]:
negative_substance_data = negative_substance_data.drop(["VALUE_AS_STRING", "OBSERVATION_SOURCE_VALUE"], axis=1)

In [17]:
negative_substance_cat = pd.get_dummies(negative_substance_data).groupby(level=0).sum()
negative_substance_cat.head()

,observation_combined_SHX Alcohol use Current,observation_combined_SHX Alcohol use Former,observation_combined_SHX Alcohol use None,observation_combined_SHX Alcohol use Unknown,observation_combined_SHX Alcohol use Within the past year,observation_combined_SHX Tobacco use Current,observation_combined_SHX Tobacco use Former smoker,observation_combined_SHX Tobacco use Light tobacco smoker,observation_combined_SHX Tobacco use Never smoker,"observation_combined_SHX Tobacco use Smoker, current status unknown",...,"observation_combined_Z68 Body mass index (BMI) 37.0-37.9, adult","observation_combined_Z68 Body mass index (BMI) 38.0-38.9, adult","observation_combined_Z68 Body mass index (BMI) 39.0-39.9, adult","observation_combined_Z68 Body mass index (BMI) 40.0-44.9, adult","observation_combined_Z68 Body mass index (BMI) 45.0-49.9, adult","observation_combined_Z68 Body mass index (BMI) 50-59.9 , adult","observation_combined_Z68 Body mass index (BMI) 50-59.9, adult","observation_combined_Z68 Body mass index (BMI) 50.0-59.9, adult","observation_combined_Z68 Body mass index (BMI) 60.0-69.9, adult","observation_combined_Z68 Body mass index (BMI) 70 or greater, adult"
PERSON_ID,,,,,,,,,,,,,,,,,,,,,
100000,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100001,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
100002,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100003,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
100004,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
negative_substance_cat.to_csv('/data/project/ubrite/covid19-hackathon/Team4_staging_area/parsed_data/negative_observation_categorical.csv'
                      , index=True)